# Generated by Django 2.1.7 on 2020-02-13 09:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personinfo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactname', models.CharField(default='', help_text='本单位联系人姓名', max_length=30, verbose_name='本单位联系人姓名')),
                ('contactphone', models.CharField(default='', help_text='联系人电话', max_length=13, verbose_name='联系人电话')),
                ('reason', models.TextField(default='', help_text='到访事由', verbose_name='到访事由')),
                ('temperature', models.CharField(default='', help_text='记录体温', max_length=13, verbose_name='记录体温')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '到访信息表',
                'verbose_name_plural': '到访信息表',
                'ordering': ['-add_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='personinfo',
            options={'ordering': ['-add_time'], 'verbose_name': '出入人员登记表', 'verbose_name_plural': '出入人员登记表'},
        ),
        migrations.RemoveField(
            model_name='personinfo',
            name='contactname',
        ),
        migrations.RemoveField(
            model_name='personinfo',
            name='contactphone',
        ),
        migrations.RemoveField(
            model_name='personinfo',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='personinfo',
            name='temperature',
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='idcard',
            field=models.CharField(default='', help_text='身份证号', max_length=30, unique=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='phone',
            field=models.CharField(default='', help_text='联系电话', max_length=13, unique=True, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='visitinfo',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitinfo', to='personinfo_app.PersonInfo', verbose_name='出入人员信息'),
        ),
    ]
