# Generated by Django 2.1.7 on 2020-02-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personinfo_app', '0002_auto_20200213_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='userid',
            field=models.CharField(default='', help_text='账号', max_length=30, verbose_name='账号'),
        ),
    ]
