# Generated by Django 2.1.7 on 2020-02-18 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personinfo_app', '0003_personinfo_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='desc',
            field=models.TextField(default='', help_text='现居住', verbose_name='现居住'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='springtime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='抵达本地时间'),
        ),
    ]
