# Generated by Django 2.1.7 on 2020-02-18 23:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='姓名', max_length=30, verbose_name='姓名')),
                ('idcard', models.CharField(default='', help_text='身份证号', max_length=30, unique=True, verbose_name='身份证号')),
                ('carid', models.CharField(default='', help_text='车牌号', max_length=30, verbose_name='车牌号')),
                ('phone', models.CharField(default='', help_text='联系电话', max_length=13, unique=True, verbose_name='联系电话')),
                ('is_local', models.BooleanField(default=False, help_text='是否本地户籍', verbose_name='是否本地户籍')),
                ('is_fromhubei', models.BooleanField(default=False, help_text='是否来自湖北', verbose_name='是否来自湖北')),
                ('comefrom', models.CharField(default='', help_text='来源地区', max_length=30, verbose_name='来源地区')),
                ('travel_mode', models.IntegerField(choices=[(1, '火车'), (2, '自驾'), (3, '汽车'), (4, '飞机')], help_text='春运出行方式', verbose_name='春运出行方式')),
                ('springtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='抵达本地时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('desc', models.TextField(default='', help_text='现居住', verbose_name='现居住')),
                ('userid', models.CharField(default='', help_text='账号', max_length=30, verbose_name='账号')),
            ],
            options={
                'verbose_name': '出入人员登记表',
                'verbose_name_plural': '出入人员登记表',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='VisitInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactname', models.CharField(default='', help_text='本单位联系人姓名', max_length=30, verbose_name='本单位联系人姓名')),
                ('contactphone', models.CharField(default='', help_text='联系人电话', max_length=13, verbose_name='联系人电话')),
                ('reason', models.TextField(default='', help_text='到访事由', verbose_name='到访事由')),
                ('temperature', models.CharField(default='', help_text='记录体温', max_length=13, verbose_name='记录体温')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('person_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitinfo', to='personinfo_app.PersonInfo', verbose_name='出入人员信息')),
            ],
            options={
                'verbose_name': '到访信息表',
                'verbose_name_plural': '到访信息表',
                'ordering': ['-add_time'],
            },
        ),
    ]
