# Generated by Django 2.1.7 on 2020-02-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personinfo_app', '0002_auto_20200220_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='carid',
            field=models.CharField(default='无', help_text='车牌号', max_length=30, verbose_name='车牌号'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='travel_mode',
            field=models.IntegerField(choices=[(0, '无'), (1, '火车'), (2, '自驾'), (3, '汽车'), (4, '飞机')], default=0, help_text='春运出行方式', verbose_name='春运出行方式'),
        ),
    ]
