# Generated by Django 2.1.7 on 2020-02-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personinfo_app', '0003_auto_20200220_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='travel_mode',
            field=models.CharField(choices=[('0', '无'), ('1', '火车'), ('2', '自驾'), ('3', '汽车'), ('4', '飞机')], default='0', help_text='春运出行方式', max_length=8, verbose_name='春运出行方式'),
        ),
    ]
